---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "webhook.selfSignedIssuer" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}

---

# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webhook.rootCACertificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "webhook.rootCACertificate" . }}
  duration: {{ .Values.pki.caDuration }}
  issuerRef:
    name: {{ include "webhook.selfSignedIssuer" . }}
  commonName: "ca.webhook.cert-manager"
  isCA: true

---

# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "webhook.rootCAIssuer" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "webhook.rootCACertificate" . }}

---

# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webhook.servingCertificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "webhook.servingCertificate" . }}
  duration: {{ .Values.pki.servingCertificateDuration }}
  issuerRef:
    name: {{ include "webhook.rootCAIssuer" . }}
  dnsNames:
  - {{ include "webhook.fullname" . }}
  - {{ include "webhook.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "webhook.fullname" . }}.{{ .Release.Namespace }}.svc
